num_workers: 16
source: channel_videos\hyperboletv.txt
destination: F:\BIG_FILES\AI_DATA\2024_STT
# destination: D:\Database\s2t-yt\source
seg_length: 20
num_segments_per_video: 15
do_shuffle_segments: true
allow_autotranscript: true
download: true
delete_full_audio_after_segmentation: true
skip_existing: true
language: "de"